var annotated_dup =
[
    [ "lost", "namespacelost.html", [
      [ "AttitudeEstimationAlgorithm", "classlost_1_1_attitude_estimation_algorithm.html", "classlost_1_1_attitude_estimation_algorithm" ],
      [ "DavenportQAlgorithm", "classlost_1_1_davenport_q_algorithm.html", "classlost_1_1_davenport_q_algorithm" ],
      [ "TriadAlgorithm", "classlost_1_1_triad_algorithm.html", "classlost_1_1_triad_algorithm" ],
      [ "QuestAlgorithm", "classlost_1_1_quest_algorithm.html", "classlost_1_1_quest_algorithm" ],
      [ "Vec2", "structlost_1_1_vec2.html", "structlost_1_1_vec2" ],
      [ "Vec3", "classlost_1_1_vec3.html", "classlost_1_1_vec3" ],
      [ "Mat3", "classlost_1_1_mat3.html", "classlost_1_1_mat3" ],
      [ "EulerAngles", "classlost_1_1_euler_angles.html", "classlost_1_1_euler_angles" ],
      [ "Quaternion", "classlost_1_1_quaternion.html", "classlost_1_1_quaternion" ],
      [ "Attitude", "classlost_1_1_attitude.html", "classlost_1_1_attitude" ],
      [ "Camera", "classlost_1_1_camera.html", "classlost_1_1_camera" ],
      [ "CentroidParams", "structlost_1_1_centroid_params.html", "structlost_1_1_centroid_params" ],
      [ "IWCoGParams", "structlost_1_1_i_w_co_g_params.html", "structlost_1_1_i_w_co_g_params" ],
      [ "CentroidAlgorithm", "classlost_1_1_centroid_algorithm.html", "classlost_1_1_centroid_algorithm" ],
      [ "DummyCentroidAlgorithm", "classlost_1_1_dummy_centroid_algorithm.html", "classlost_1_1_dummy_centroid_algorithm" ],
      [ "CenterOfGravityAlgorithm", "classlost_1_1_center_of_gravity_algorithm.html", "classlost_1_1_center_of_gravity_algorithm" ],
      [ "IterativeWeightedCenterOfGravityAlgorithm", "classlost_1_1_iterative_weighted_center_of_gravity_algorithm.html", "classlost_1_1_iterative_weighted_center_of_gravity_algorithm" ],
      [ "KVectorPair", "structlost_1_1_k_vector_pair.html", "structlost_1_1_k_vector_pair" ],
      [ "KVectorIndex", "classlost_1_1_k_vector_index.html", "classlost_1_1_k_vector_index" ],
      [ "PairDistanceKVectorDatabase", "classlost_1_1_pair_distance_k_vector_database.html", "classlost_1_1_pair_distance_k_vector_database" ],
      [ "MultiDatabase", "classlost_1_1_multi_database.html", "classlost_1_1_multi_database" ],
      [ "MultiDatabaseBuilder", "classlost_1_1_multi_database_builder.html", "classlost_1_1_multi_database_builder" ],
      [ "GeneratedStar", "classlost_1_1_generated_star.html", "classlost_1_1_generated_star" ],
      [ "CentroidComparison", "classlost_1_1_centroid_comparison.html", "classlost_1_1_centroid_comparison" ],
      [ "PromptedOutputStream", "classlost_1_1_prompted_output_stream.html", "classlost_1_1_prompted_output_stream" ],
      [ "Image", "classlost_1_1_image.html", "classlost_1_1_image" ],
      [ "PipelineOptions", "classlost_1_1_pipeline_options.html", null ],
      [ "PipelineInput", "classlost_1_1_pipeline_input.html", "classlost_1_1_pipeline_input" ],
      [ "GeneratedPipelineInput", "classlost_1_1_generated_pipeline_input.html", "classlost_1_1_generated_pipeline_input" ],
      [ "PngPipelineInput", "classlost_1_1_png_pipeline_input.html", "classlost_1_1_png_pipeline_input" ],
      [ "PipelineOutput", "structlost_1_1_pipeline_output.html", "structlost_1_1_pipeline_output" ],
      [ "StarIdComparison", "structlost_1_1_star_id_comparison.html", "structlost_1_1_star_id_comparison" ],
      [ "Pipeline", "classlost_1_1_pipeline.html", "classlost_1_1_pipeline" ],
      [ "DatabaseOptions", "classlost_1_1_database_options.html", null ],
      [ "IRUnidentifiedCentroid", "classlost_1_1_i_r_unidentified_centroid.html", "classlost_1_1_i_r_unidentified_centroid" ],
      [ "PairDistanceInvolvingIterator", "classlost_1_1_pair_distance_involving_iterator.html", "classlost_1_1_pair_distance_involving_iterator" ],
      [ "StarIdAlgorithm", "classlost_1_1_star_id_algorithm.html", "classlost_1_1_star_id_algorithm" ],
      [ "DummyStarIdAlgorithm", "classlost_1_1_dummy_star_id_algorithm.html", "classlost_1_1_dummy_star_id_algorithm" ],
      [ "GeometricVotingStarIdAlgorithm", "classlost_1_1_geometric_voting_star_id_algorithm.html", "classlost_1_1_geometric_voting_star_id_algorithm" ],
      [ "PyramidStarIdAlgorithm", "classlost_1_1_pyramid_star_id_algorithm.html", "classlost_1_1_pyramid_star_id_algorithm" ],
      [ "CatalogStar", "classlost_1_1_catalog_star.html", "classlost_1_1_catalog_star" ],
      [ "Star", "classlost_1_1_star.html", "classlost_1_1_star" ],
      [ "StarIdentifier", "classlost_1_1_star_identifier.html", "classlost_1_1_star_identifier" ]
    ] ]
];