version: "3.9"
services:
  lost:
    container_name: lost
    build: .
    image: kjy5/lost:latest
    working_dir: /root/lost
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /root/lost