version: 2.1

references:
  workspace_root: &workspace_root
                    ~/lost
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  lost:
    docker:
      - image: cimg/base:stable
    working_directory: ~/lost

jobs:
  build:
    executor: lost
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Build files
          command: |
            make all
      - run: |
          cd build
          make
  test:
    executor: lost
    steps:
      - *attach_workspace
      - run:
          name: Run unit tests
          command: |
            ./lost_test

  lint:
    working_directory: ~/lost
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: install cpplint
          command: sudo pip install cpplint
      - run: make cpplint
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint
      - test:
          requires:
            - build
