.TH DATABASE 3 "06 November 2021" 

.SH NAME

database \- builds a database

.SH SYNOPSIS

\fBdatabase\fP [--mag \fImax-magnitude\fP | --stars \fInum-stars\fP] [--kvector --kvector-min-distance \fImin\fP --kvector-max-distance \fImax\fP --kvector-distance-bins \fInum-bins\fP] \fIoutput-path\fP
.br

.SH DESCRIPTION

\fBdatabase\fP generates a database (a subset of the star catalog), which is used to compare unidentified stars against. The greater star catalog contains about 9000 stars, which
can be limited in the database by filtering the stars out with a \fImax-magnitude\fP or by getting the \fInum-stars\fP brightest stars in the catalog. There are several different methods of
constructing a database. This database is then generated into the file \fIoutput-path\fP.

.SS Options

.TP
\fB--mag\fP \fImax-magnitude\fP
Limits database to stars below \fImax-magnitude\fP (brighter stars have lower magnitudes).

.TP
\fB\-\-stars\fP \fInum-stars\fP
Limits database to the \fInum-stars\fP brightest stars in the catalog.

.TP
\fB--kvector\fP
Uses the kvector method of building a database.

.TP
\fB--kvector-min-distance \fImin\fP
Sets the minimum distance bin in the kvector building method to \fImin\fP.

.TP
\fB--kvector-max-distance\fP \fImax\fP
Sets the maximum distance bin in the kvector building method to \fImax\fP.

.TP
\fB--kvector-distance-bins\fP \fInum-bins\fP
Sets the number of distance bins in the kvector building method to \fInum-bins\fP.

.TP
\fIoutput-path\fP
The file to output the database to. Use - for stdout.

.SH SEE ALSO
pipeline(3)