.TH PIPELINE 3 "06 November 2021" 

.SH NAME

pipeline \- builds a pipeline of the star identification process

.SH SYNOPSIS

\fBpipeline\fP --png \fIfilepath\fP (--focal-length \fIlength\fP --pixel-size \fIsize\fP) | --fov \fIdegrees\fP [--centroid-algo \fIalgorithm\fP [--centroid-dummy-stars \fInum-stars\fP]] [--centroid-mag-filter \fImin-mag\fP] 
[--database \fIfilename\fP] [--star-id-algo \fIalgo\fP (--gv-tolerance \fIdegrees\fP | --py-tolerance \fIdegrees\fP --false-stars \fInum\fP --max-mismatch-prob \fIprobability\fP)] [--attitude-algo \fIalgo\fP] [--plot \fIoutput-path\fB]
.br
\fBpipeline\fP --generate[=\fInum-images\fP] [--horizontal-res \fIres\fP] [--vertical-res \fIres\fP] [--horizontal-fov \fIdegrees\fP] [--ref-brightness \fImag\fP] [--spread-stddev \fIstddev\fP] [--noise-stddev \fIstddev\fP] [--boresight-right-asc \fIascension\fP] [--boresight-dec \fIdeclination\fP] [--boresight-roll \fIroll\fP] 
[--centroid-algo \fIalgorithm\fP [--centroid-dummy-stars \fInum-stars\fP]] [--centroid-mag-filter \fImin-mag\fP] 
[--database \fIfilename\fP] [--star-id-algo \fIalgo\fP (--gv-tolerance \fIdegrees\fP | --py-tolerance \fIdegrees\fP --false-stars \fInum\fP --max-mismatch-prob \fIprobability\fP | --prev-attitude \fIattitude\fP --uncertainty \fIradius\fP (--tracking-compare-threshold \fIthreshold\fP))] [--attitude-algo \fIalgo\fP] [--plot \fIoutput-path\fB]

.SH DESCRIPTION

\fBpipeline\fP is the command to set the different stages of the star identification pipeline. An image can be
taken in as input from \fIfilepath\fP, or image(s) can be generated according to various parameters. There are five main stages to the pipeline:
--centroid, --centroid-mag-filter, --id, --database, and --attitude. The --centroid option allows the user to
choose which centroiding algorithm to use, while the --centroid-mag-filter option allows the user to filter out candidate
centroids below a certain magnitude. The --database option allows the user to specificy which file to use as the database.
The --id option runs the star identification algorithm, and the --attitude option determines the orientation of the
cubesat in space.

.SS Options

.TP
\fB--png\fP \fIfilepath\fP
Identify the png image at the given \fIfilepath\fP.

.TP
\fB--focal-length\fP \fIlength\fP
The focal length of the camera that took the picture (in mm).

.TP
\fB--pixel-size\fP \fIsize\fP
The pixel size of the camera that took the picture (in \[*m]m).

.TP
\fB--fov\fP \fIdegrees\fP
The field of view of the camera that took the picture (in degrees). Defaults to 20 deg if option is not selected.

.TP
\fB--centroid-algo\fP \fIalgo\fP
Runs the \fIalgo\fP centroiding algorithm. Recognized options are: dummy (random centroid algorithm), cog (center of gravity), and iwcog (iterative weighted center of gravity).  Defaults to dummy if option is not selected.

.TP
\fB--centroid-dummy-stars\fP \fInum-stars\fP
Runs the dummy centroiding algorithm (random centroid algorithm) with \fInum-stars\fP stars centroided. Defaults to 5 if option is not selected.

.TP
\fB--centroid-mag-filter\fP \fImin-mag\fP
Will not consider candidate as centroid if its magnitude is below \fImin-mag\fP.

.TP
\fB--star-id-algo\fP \fIalgo\fP
Runs the \fIalgo\fP star identification algorithm. Current options are "dummy", "gv", "pyramid", and "tracking". Defaults to "pyramid" if option is not selected.

.TP
\fB--angular-tolerance\fP [\fItolerance\fP] Sets the estimated angular centroiding error tolerance,
used in some star id algorithms, to \fItolerance\fP degrees. Defaults to 0.04 degrees.

.TP
\fB--false-stars\fP \fInum\fP
\fInum\fP is the estimated number of false stars in the whole sphere for the pyramid scheme star identification algorithm. Defaults to 500 if option is not selected.

.TP
\fB--max-mismatch-prob\fP \fIprobability\fP
\fIprobability\fP is the maximum allowable probability of an incorrect star identification, for star id algorithms which support it. Defaults to 0.001.

.TP
\fB--prev-attitude\fP \fIattitude\fP
\fIattitude\fP is the known previous attitude for tracking mode. Should give ra, dec, and roll as a comma-separated list: "ra,dec,roll."

.TP
\fB--uncertainty\fP \fIradius\fP
For tracking mode. \fIradius\fP gives the boundary for how much the field of view could have rotated. Defaults to 0.001 if not selected. Must be nonnegative.

.TP
\fB--tracking-compare-threshold\fP \fIthreshold\fP
\fIthreshold\fP is the threshold for comparing floats for tracking mode. Defaults to 0.0001 if no value is given.

.TP
\fB--attitude-algo\fP \fIalgo\fP
Runs the \fIalgo\fP algorithm for the attitude stage of the pipeline. Current options are "dqm" (Davenport Q) and "triad". Defaults to dqm.

.TP
\fB--generate\fP[=\fInum-images\fP]
Generates \fInum-images\fP many images. Mutually exclusive with \fB--png\fP.

.TP
\fB--generate-x-resolution\fP \fIpixels\fP
Sets the horizontal resolution of the generated image(s) to \fIpixels\fP. Defaults to 1024.

.TP
\fB--generate-y-resolution\fP \fIpixels\fP
Sets the vertical resolution of the generated image(s) to \fIpixels\fP. Defaults to 1024.

.TP
\fB--generate-reference-brightness\fP \fIobserved-brightness\fP
A star with magnitude 0 in the generated image will have have brightness \fIobserved-brightness\fP. An observed brightness of 1 fully saturates the pixel at the center of the star (completely white). Defaults to 100.

.TP
\fB--generate-spread-stddev\fP \fIstddev\fP
Sets the standard deviation of the Gaussian distribution we use to approximate the distribution of photons received from each star. Defaults to 1.0.

.TP
\fB--generate-shot-noise\fP \fItrue|false\fP
Enables or disables shot noise simulation in generated images. Defaults to true.

.TP
\fB--generate-dark-current\fP \fInoise-level\fP
Set observed brightness of dark current in the image, from 0 (no dark noise) to 1 (whole image pure white). Defaults to 0.1. cf \fB--generate-sensitivity\fP to control shot noise intensity.

.TP
\fB--generate-sensitivity\fP \fIsensitivity\fP
Controls the simulated camera sensitivity for generated images. This only has an observable effect when shot noise is enabled (cf \fB--generate-shot-noise\fP). A higher sensitivity means that fewer photons can cause the same observed brightness on the sensor, so variation in number of photons causes more shot noise. Brightness is normalized according to \fB--generate-reference-brightness\fP so that adjusting sensitivity does not change observed brightness.

.TP
\fB--generate-read-noise-stddev\fP \fIstddev\fP
Sets the standard deviation of Gaussian noise in the generated image(s) to \fIstddev\fP. Noise is measured in observed brightness, where 1 is the difference between pure white and pure black. Defaults to 0.05.

.TP
\fB--generate-ra\fP, \fB--generate-de\fP, \fB--generate-roll\fP \fIdegrees\fP
Set the right ascension, declination, and roll of the generated image.

.TP
\fB--generate-exposure\fP \fIexposure-time\fP
Controls the exposure time of generated images. Only useful wrt motion blur. Default is 0 (motion blur disabled).

.TP
\fB--generate-blur-ra\fP, \fB--generate-blur-de\fP, \fB--generate-blur-roll\fP \fIdegrees\fP
When motion blur is enabled, this is the change in attitude per unit time.

.TP
\fB--generate-readout-time\fP \fIreadout-time\fP
Rolling shutter readout time for generated images. This is the time it takes from starting to capture the first row until finishing capturing the last row. Defaults to 0 (rolling shutter simulation disabled).

.TP
\fB--generate-false-stars\fP \fInum-false-stars\fP
The number of false stars generated. All are placed uniformly randomly around the celestial sphere. Defaults to 0 (no false stars generated)

.TP
\fB--generate-false-min-mag\fP \fIminimum-magnitude\fP
The minimum (weakest) magnitude that generated false stars should have. Defaults to 8.0.

.TP
\fB--generate-false-max-mag\fP \fImaximum-magnitude\fP
The maximum (strongest) magnitude that generated false stars should have. Defaults to 1.0.

.TP
\fB--generate-oversampling\fP \fInum-samples\fP
Peform \fInum-samples\fP many samples per pixel when generating images. Effectively performs antialiasing. \fInum-samples\fP must be a perfect square. Default 4.

.TP
\fB--generate-seed\fP \fIseed\fP
An integer seed to pass to the random number generator used during image generation.

.TP
\fB--plot-raw-input\fP=[\fIpath\fP]
Argument is optional. Plots raw BW input image to PNG. Prints to \fIpath\fP. Defaults to stdout if if \fIpath\fP is not given.

.TP
\fB--plot-input\fP=[\fIpath\fP]
Argument is optional. Plots annotated input image to PNG. Prints to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--plot-output\fP=[\fIpath\fP]
Argument is optional. Plot output to PNG. Prints to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--print-centroids\fP=[\fIpath\fP]
Argument is optional. Plot output to PNG. Prints to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--compare-centroids\fP=[\fIpath\fP]
Argument is optional. Print list of centroids to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--compare-stars\fP=[\fIpath\fP]
Argument is optional. Compare lists of identified stars. Prints to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--print-attitude\fP=[\fIpath\fP]
Argument is optional. Print the determined ra, de, and roll to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--compare-attitude\fP=[\fIpath\fP]
Argument is optional. Compare expected to actual attitude. Prints to \fIpath\fP. Defaults to stdout if \fIpath\fP is not given.

.TP
\fB--centroid-compare-threshold\fP \fIthreshold\fP
Sets the threshold for the centroid comparing algorithms

.TP
\fB--attitude-compare-threshold\fP \fIthreshold\fP
Sets the threshold for the attitude comparing algorithms

.TP
\fB--database\fP \fIfilename\fP
Chooses \fIfilename\fP as the database to compare stars against.

.TP
\fB--help\fI
Prints the contents of the manual entry for the command to the terminal.

.SH SEE ALSO
database(3)
