name: Build and Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: huskysat/lost:latest

    steps:
    - uses: actions/checkout@v3
    - name: 🛠 Build
      run: make -j$(($(nproc)+1))

  test:
    runs-on: ubuntu-latest
    container: huskysat/lost:latest

    steps:
    - uses: actions/checkout@v3
    - name: 📊 Unit Tests
      run: make test -j$(($(nproc)+1))